apiVersion: v1
kind: Pod
metadata:
  name: cve-pod-host-users
spec:
  terminationGracePeriodSeconds: 1
  containers:
  - name: container1
    image: debian
    command: ["sleep", "infinity"]
    securityContext:
      capabilities:
        add: ["SYS_ADMIN"]
